author: Matt Reach # 作者
description: Matt Reach's blog
keyword: 许乾隆,Matt Reach
# favicon:

excerpt_link: Read more

menu:
 Home: /
 #Archives: /archives/
 Tags: /tags/
 Projects: /project/
 About: /about/
 

# highlight
#tomorrow https://highlightjs.org/  http://www.bootcdn.cn/highlight.js/
highlight:
  zenburn

# catalog
catalog: false

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: debugly
gitment_repo: debugly.github.io
gitment_oauth_id: ef799a3a8ea3c51cd976
gitment_oauth_secret: 0c9fe417f7acc5d01b90186f949fee2faefffc30

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

# baidu_id: 

# postnav
postnav: true

about: 
  banner: /css/images/about_bg.jpg
  avatar: /css/images/icon_about.jpg
  github_username: debugly