author: Matt Reach # 作者
description: Matt Reach's blog
keyword: 许乾隆,Matt Reach
# favicon:

excerpt_link: Read more

menu:
 Home: /
 Archives: /archives/
 Tags: /tags/
 Projects: /project/
 About: /about/
 

# highlight
highlight:
  tomorrow

# catalog
catalog: false

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: debugly
gitment_repo: debugly.github.io
gitment_oauth_id: ce1d755873d77e993024
gitment_oauth_secret: 47471beab9dc3898e0310556a7b239db624fe919

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

# postnav
postnav: true

about: 
  banner: /assets/about_bg.jpg
  avatar: /assets/icon_about.jpg
  # description: An iOS Developer.
  # Links
  # weibo_username: yanm1ng
  # twitter_username: yanm1ng
  github_username: debugly
  # zhihu_username: yummy1121
  # douban_username: yanm1ng